/*
 * File: app/view/LoginWindow.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WeatherApp.view.LoginWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.loginwindow',

    requires: [
        'WeatherApp.view.LoginWindowViewModel',
        'WeatherApp.view.LoginWindowViewController',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    controller: 'loginwindow',
    viewModel: {
        type: 'loginwindow'
    },
    autoShow: true,
    height: 250,
    width: 400,
    closable: false,
    title: 'Login',
    titleAlign: 'center',

    items: [
        {
            xtype: 'form',
            reference: 'loginform',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Username',
                    allowBlank: false,
                    allowOnlyWhitespace: false,
                    blankText: 'Please enter your username.'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Password',
                    inputType: 'password',
                    allowBlank: false,
                    allowOnlyWhitespace: false,
                    blankText: 'Please enter your password.'
                },
                {
                    xtype: 'button',
                    formBind: true,
                    text: 'Login',
                    listeners: {
                        click: 'onLoginClick'
                    }
                }
            ]
        }
    ]

});