/*
 * File: app/view/MainViewViewController.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WeatherApp.view.MainViewViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.mainview',

    onGetWeatherByCityNameClick: function(button, e, eOpts) {

        var cityField = this.getView().lookup('cityNameText');
        var cityName = cityField.getValue();

        if(cityName ==='') {
            console.log('city name can not be empty');

        } else {
            // show forecast overview panel
            var panel = this.getView().lookup('forecastresultpanel');
            panel.expand();

            // setup result grid
            var resultGrid = panel.down('#results');
            resultGrid.setTitle('Current weather in '+ cityName);

            var store = resultGrid.getStore();
            store.removeAll();
            resultGrid.setHidden(false);
            resultGrid.setLoading(true);


            store.load({
                params: {
                    q: cityName
                },
                callback: function (records, options, success) {
                    console.log('loading data from openweather completed...');
                    if (success) {
                        var ct = records.length, it = 0;
                        while (it < ct) {
                            console.log(records[it]);
                            it++;
                        }
                        resultGrid.setLoading(false);
                    }
                }
            });

        }
    }

});
