/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WeatherApp.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'WeatherApp.view.MainViewViewModel',
        'WeatherApp.view.MainViewViewController',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.view.Table'
    ],

    controller: 'mainview',
    viewModel: {
        type: 'mainview'
    },

    items: [
        {
            xtype: 'panel',
            layout: 'fit',
            title: 'Weather Forecast',
            items: [
                {
                    xtype: 'tabpanel',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Current Weather',
                            items: [
                                {
                                    xtype: 'panel',
                                    layout: 'accordion',
                                    title: '',
                                    items: [
                                        {
                                            xtype: 'panel',
                                            title: 'Weather By City',
                                            items: [
                                                {
                                                    xtype: 'form',
                                                    padding: 50,
                                                    title: '',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            formBind: false,
                                                            reference: 'cityNameText',
                                                            fieldLabel: '',
                                                            validateOnChange: false,
                                                            allowBlank: false,
                                                            allowOnlyWhitespace: false,
                                                            blankText: 'City Name is required!',
                                                            emptyText: 'Enter City Name...'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            formBind: true,
                                                            width: 150,
                                                            text: 'Get Forecast',
                                                            listeners: {
                                                                click: 'onGetWeatherByCityNameClick'
                                                            }
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            title: 'Weather By Zip',
                                            items: [
                                                {
                                                    xtype: 'form',
                                                    padding: 50,
                                                    title: '',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            formBind: true,
                                                            fieldLabel: '',
                                                            emptyText: 'Enter zip code...',
                                                            selectOnFocus: true,
                                                            validateBlank: true
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            width: 150,
                                                            text: 'Get Forecast'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            title: 'Weather By Co-ordinates',
                                            items: [
                                                {
                                                    xtype: 'form',
                                                    padding: 50,
                                                    title: '',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            formBind: true,
                                                            fieldLabel: '',
                                                            emptyText: 'Enter geographical coordinates...',
                                                            selectOnFocus: true,
                                                            validateBlank: true
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            width: 150,
                                                            text: 'Get Forecast'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            reference: 'forecastresultpanel',
                                            itemId: 'forecastResultPanel',
                                            title: 'Search Results',
                                            dockedItems: [
                                                {
                                                    xtype: 'gridpanel',
                                                    dock: 'top',
                                                    hidden: true,
                                                    itemId: 'results',
                                                    store: 'OpenweatherStore',
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'longitude',
                                                            text: 'Longitude'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'latitude',
                                                            text: 'Latitude'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            width: 150,
                                                            dataIndex: 'temperature',
                                                            text: 'Temperature'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'pressure',
                                                            text: 'Pressure'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'humidity',
                                                            text: 'Humidity'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            width: 150,
                                                            dataIndex: 'cloudcover',
                                                            text: 'Cloud Cover'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            width: 120,
                                                            dataIndex: 'windspeed',
                                                            text: 'Wind Speed'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Forecast'
                        },
                        {
                            xtype: 'panel',
                            title: 'About Us'
                        }
                    ]
                }
            ]
        }
    ]

});