/*
 * File: app/model/WeatherModel.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('WeatherApp.model.WeatherModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.String'
    ],

    fields: [
        {
            type: 'string',
            mapping: 'coord.lon',
            name: 'longitude'
        },
        {
            type: 'string',
            mapping: 'coord.lat',
            name: 'latitude'
        },
        {
            type: 'string',
            mapping: 'main.temp',
            name: 'temperature'
        },
        {
            type: 'string',
            mapping: 'main.pressure',
            name: 'pressure'
        },
        {
            type: 'string',
            mapping: 'main.humidity',
            name: 'humidity'
        },
        {
            type: 'string',
            mapping: 'clouds.all',
            name: 'cloudcover'
        },
        {
            type: 'string',
            mapping: 'wind.speed',
            name: 'windspeed'
        }
    ]
});